version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_formation
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: